services:
  app:
    image: php:8.2-apache
    container_name: meupdv-php
    volumes:
      - ./app:/var/www/html
      - ./data:/app_data
    expose:
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy
    container_name: meupdv-caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./app:/var/www/html 
    ports:
      - "8070:80"
    depends_on:
      - app
    restart: unless-stopped
